# Generated by Django 5.2.6 on 2025-09-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuração Geral', max_length=100)),
                ('speech_api_key', models.CharField(max_length=255)),
                ('speech_api_region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('substantivo', 'Substantivo'), ('verbo', 'Verbo'), ('adjetivo', 'Adjetivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning_English.word')),
            ],
        ),
    ]
